### ISSUE TITLE
유효성 검사를 어느 영역에서 진행해야 하는가 ? (DTo vs Entity) 

### ISSUE THREAD

**Issue by kkj5158** [kkj5158/Project_Spring_JPA_board#2]

**Comment by kkj5158** [comment]
처음에는 유효성 검사를 Entity 상에서 진행하였다. 하지만 이후에 예외처리 과정에서 dto상에서의 유효성검사로 변경하고 , 엔티티에서 진행되는 유효성검사들은 모두 풀었다. 프론트단에서 정보들이 넘어오는 만큼, 처음 넘어오는 정보들의 유효성을 검사하는것이 더욱 타당해 보였기에 DTO에서 유효성 검사를 진행하는 방식으로 리팩토링 하였다.

**Comment by taetoo** [comment]
일단 유효성 검사는 모든 레이어에서 진행하는게 좋을 것 같습니다.
이유는 우선 컨트롤로 무조건 정상적인 요청이 들어올 것이라는 보장이 없기 때문에 유효성 검사가 필요할 것이라 생각하고, 또한 프로그래머의 단순 실수가 발생할 수도 있고 더불어 각 레이어는 유효성 검사에 대한 책임을 갖기 때문입니다.
만약 컨트롤러로 정상적이 요청이 들어온다는 가정을 할 경우 서비스에서는 컨트롤러에서 정상적인 요청이 들어온다고 가정을 해버렸기 때문에 컨트롤러에 의존적일 수 밖에 없고, 서비스에서 따로 유효성 검사를 하지 않고 DTO에서만 유효성 검사를 진행하게 될 경우 유효성에 걸리지 않는 정상적이 않은 값이 DB로 insert 될 수도 있을 것입니다. 
결론을 내리자면 둘 다 진행하는 것이 좋다는 것이 제 소견입니다.

⭐️ 참고자료
[https://www.baeldung.com/spring-service-layer-validation](url)
