### ISSUE TITLE
ResponseEntity 사용에 대하여 _ HTTP STATUS Code는 직접 넣어주어야 하는가? 

### ISSUE THREAD

**Issue by kkj5158** [kkj5158/Project_Spring_JPA_board#3]
처음으로 반환값을  ResponseEntity 를 사용하여 반환하여 봄. 
Rest api와 관련하여서 다음의 글을 보고서 모든 반환값을 ResponseEntity 포장하여서 반환하였다. 

[[https://devlog-wjdrbs96.tistory.com/197]]

해당 블로그에서는 httpstatus를 final static의 형식으로 미리 클래스에 저장해두고, 상황에 따라서 컨트롤러에서 넣어주는 방식을 사용하였다. 
여기서 궁금한 지점은 , 개발자가 직접 상황을 판단하여서 미리 클래스내에서 작성되어있는 상태코드를 클래스 변수의 형태로 넘겨주는 것이 적절한가? 이다. 

상태코드를 http 에서 꺼내오는 방식이 더욱 적절해보이지만, 어떤 방식으로 반환되는 http의 상태코드를 찾아와서 해당 상태코드를 ResponseEntity 로 포장하여서 반환하는지 알아내지 못했다.

**Comment by taetoo** [comment]
음.. 좋은 고찰인 것 같습니다. 우선 보통 http 상태코드와 같은 경우는 팀컨벤션일 가능성이 높습니다. 결국 회사마다 규칙이 있을 것이라는 것이죠.
아래 참고자료를 보시고 한번 고민해보시면 좋을 것 같습니다.

⭐️ 참고자료
[https://stackoverflow.com/questions/39636795/http-status-code-4xx-vs-5xx](url)
