### ISSUE TITLE
REST API + JWT 설계구조를 가진다면 회원가입/로그인 api 명명이름은 어떻게 지어야 하는가? 

### ISSUE THREAD

**Issue by kkj5158** [kkj5158/Project_Spring_JPA_board#4]
REST에 대해서 배우고 고민하기 전에는 항상 로그인과 회원가입 api의 이름은 자연스럽게 login 과 signup으로 지었다. 하지만 REST는 그 이름에도  철학이 담겨있듯이 Resource(자원)을 중점으로 api를 설계하고 행동을 이름에서 배제하는 api 규칙이다. 그러므로 처음에는 /user의 형태로 이름을 지었다. 하지만 로그인과 회원가입 모두 post method를 사용하므로 이를 결국 구분해야 했고. 결론적으로는 다음과 같이 api를 명명했다. 

로그인 user/login
회원가입 user/signup

자료를 찾아보니. auth라는 이름을 쓰는 api도 존재했다. 만약 jwt를 하나의 자원으로 본다면 로그인과 회원가입의 api 명세서를 어떻게 명명 옳은 것인지 궁금해진다.

**Comment by taetoo** [comment]
Restful한 네이밍은 사실 REST 특징을 고려하여 명명하는 것이 가장 좋다고 생각합니다.
일단 이 부분도 결국 컨벤션을 정하고 진행하는 것이기 때문에 멀리가서 고민하지 마시고, 큰 서비스 회사들의 REST API 컨벤션을 통해서 공부해 보시는 것은 어떨까요?
아래 레퍼런스를 참고하시면 어렵지 않게 Reat api 컨벤션에 대해 공부해 보실 수 있을거라 생각합니다.

⭐️ 참고자료
[https://restfulapi.net/resource-naming/](url)
[https://learn.microsoft.com/en-us/azure/architecture/best-practices/api-design](url)
