### ISSUE TITLE
security를 활용한 인증과 인가 

### ISSUE THREAD

**Issue by kkj5158** [kkj5158/Project_Spring_JPA_board#5]
챗 gpt를 통해서, 

기존 프로젝트에서 JWT를 통해서 인증하는 과정을 스프링 시큐리티 인증과정으로 변경하고 싶어. 궁금한점은 기존 프로젝트에서는 HTTP REQUEST 객체를 서비스단까지 내려서 거기에서 JWT를 복호화해서 사용자 정보를 확인해서 인가를 구현한 상황이야. 이 상황을 시큐리티로 변경하는 과정은 시큐리티의  SecurityContextHolder 을 사용하여서 유저의 정보를 꺼내오는 방식으로 바꾸는 과정일까 ?
>>>
네, 맞습니다. 기존의 JWT 인증 방식을 Spring Security로 변경하는 경우, SecurityContextHolder를 사용하여 사용자 정보를 저장하고 인가를 처리하게 됩니다.

기존의 방식에서는 HTTP Request 객체를 서비스 계층까지 전달하여 JWT 토큰을 추출하고, 이를 복호화하여 사용자 정보를 확인하고 인가를 처리하는 방식이었습니다. 이 방식은 일반적으로 JWT를 직접 사용하는 경우에 많이 쓰이는 방식입니다.

하지만 Spring Security에서는 SecurityContextHolder를 사용하여 현재 인증된 사용자 정보를 저장하고 인가를 처리합니다. SecurityContextHolder는 Thread-Local 방식으로 작동하며, 현재 스레드에서만 접근 가능한 저장소입니다. SecurityContextHolder에 저장된 인증 정보는 Spring Security가 인가 처리를 수행할 때 사용됩니다.

따라서, Spring Security로 변경하는 경우 JWT 토큰에서 추출한 사용자 정보를 SecurityContextHolder에 저장하고, Spring Security에서 제공하는 AccessDecisionManager 등을 사용하여 인가 처리를 수행하게 됩니다. 이 방식은 Spring Security의 기능을 최대한 활용하여 보안을 강화하고, 유지 보수성을 높이는 것을 목적으로 합니다.

**Comment by taetoo** [comment]
chatGPT가 잘 설명해주었네요 😊
지승님이 level 4에서 진행해주신 springsecurity 디렉토리 안에 클래스들을 살펴보았는데, 전체적으로 잘 진행해주신 것 같고, 인증과 인가 실패에 따른 리다이렉트까지 구현해 놓으신 부분도 정말 잘 진행해 주셨습니다.👍🏻
추가로 프론트와 협업에 들어가면 spring security 를 사용한다는 전제하에 **CORS** 정책문제가 생길 가능성이 높은데, 이 부분에 대해서 이번주차에 집고 넘어가시는게 좋을 것 같습니다. 
이번주도 화이팅 입니다!!
